### PR TITLE
Add support for Jenkins

### LINKED ISSUE #25: Support Jenkins
Any plan to support Jenkins? What would it take to make this working?

### PR DESCRIPTION
**Pull request by kterada0509**
## WHAT

- add(core): Support Jenkins as new CI

## WHY

Fixed #25

### CODE REVIEW

**Comment by b4b4r07** [comment]
Thank you for your contribution! I’ll review this later

**Comment by b4b4r07** [comment]
Sorry for late response.

**Comment by b4b4r07** [comment]
@kterada0509 

Could you solve confits..? 🙇

**Comment by kterada0509** [comment]
@b4b4r07 
Thanks for review.
I fixed conflict.

**Comment by b4b4r07** [comment]
I'll review this again today.

**Comment by b4b4r07** [comment]
Sorry for the late response. And thank you for the contribution!

**Pull request merged**
