### PR TITLE
Add support for GitHub Actions workflow triggered by Pull Request

### PR DESCRIPTION
**Pull request by dtan4**
## WHAT

This change enables tfnotify to put comments on GitHub Pull Request, from GitHub Actions **triggered by the same Pull Request (`on.pull_request`)**.

### Screenshot

image

### Example GitHub Actions workflow

```yaml
# .github/workflows/terraform-plan.yaml

name: "terraform plan for AWS"
on:
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Terraform Init"
        run: terraform init
      - name: "Terraform Plan"
        run: terraform plan | tfnotify --config tfnotify.yaml plan
```

## WHY

Current GitHub Actions support doesn't support workflow triggered by Pull Request because it doesn't read the target Pull Request number. Therefore, we have to use "branch push (`on.branches`)" as workflow trigger.
Actually, tfnotify with branch-triggered workflow can also put the comment on the Pull Request timeline. However, it lacks some tfnotify features, like putting labels like `no-changes` based on `terraform plan` result. Therefore, to provide the equivalent experience to GitHub Actions users as well as other CIs, it's better to implement native Pull Request support.

### CODE REVIEW

**Comment by b4b4r07** [comment]
Thanks! Could you look the test cases with failing?

**Comment by dtan4** [comment]
Sorry for the delay... fixed the test!

**Comment by mijime** [comment]
I'd really like to see you merge this great PR, is there anything I can do to help?

**Review by dragon3 — APPROVED** [review]
@b4b4r07 @dtan4 
Looks good to me 👍 and I'd like to get this change as well 😄 

I found this change is almost same as https://github.com/mercari/tfnotify/pull/75 , so once we merge this pull request, we can close the #75 .

**Review by KeisukeYamashita — APPROVED** [review]
LGTM, merging as no activitity 🙏

**Pull request merged**
