### PR TITLE
Add support for gitlab and gitlab-ci

### LINKED ISSUE #20: Support Gitlab CI
Is Gitlab CI support planned?
This is a popular CI so I think it will be interesting to do the support :)

Thanks for your work 👍

### PR DESCRIPTION
**Pull request by kterada0509**
## WHAT
Fixed #20 
- add(core): Support GitLab CI as new CI
- Add support for GitLab

## WHY
To use tfnotify in GitLab and GitLab CI

### CODE REVIEW

**Comment by andshun** [comment]
@dtan4 @b4b4r07 ping

**Comment by b4b4r07** [comment]
@andshun 

Nice work. I'll review this soon. Sorry for waiting you.

Please solve conflicts 🙏

**Comment by b4b4r07** [comment]
@kterada0509 

Nice work. I'll review this soon. Sorry for waiting you.

Please solve conflicts 🙏

**Comment by kterada0509** [comment]
@b4b4r07 
Thanks, I will fix this conflict after merged PR https://github.com/mercari/tfnotify/pull/39 .

**Comment by kterada0509** [comment]
@b4b4r07 
I fixed conflict.
please review when you have time.

**Comment by b4b4r07** [comment]
I'll upload the binary.

**Pull request merged**
