### PR TITLE
Add TeamCity CI support

### PR DESCRIPTION
**Pull request by genert**
Self-explanatory title.

### CODE REVIEW

**Comment by Genert** [comment]
@dtan4 @b4b4r07 ping

**Comment by b4b4r07** [comment]
Sorry for late reply.. I'll review this soon.

**Comment by b4b4r07** [comment]
@Genert 

Could you follow the changelog format like `VERB(TARGET) MESSAGE`. For example, in your case `add(core) Support TeamCity as new CI`

**Comment by Genert** [comment]
Updated the commit message to match with changelog.

**Comment by b4b4r07** [comment]
Sorry for late response.

**Pull request merged**
