### PR TITLE
Correct CODEOWNERS to refer @b4b4r07

### PR DESCRIPTION
**Pull request by dtan4**
## WHAT

Correct CODEOWNERS to refer both @dtan4 and @b4b4r07 

## WHY

Following to [the current CODEOWNERS settings](https://github.com/mercari/tfnotify/blob/8bac913495b5b449ea012c999c7673f63f95f934/.github/CODEOWNERS), only @dtan4 is assigned as default reviewer.

To assign multiple members, they need to be written in the same line.

https://help.github.com/articles/about-codeowners/

```
# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
# @global-owner1 and @global-owner2 will be requested for
# review when someone opens a pull request.
*       @global-owner1 @global-owner2
```

### CODE REVIEW

**Comment by b4b4r07** [comment]
Oops, CI failed. I'll kick it again

**Comment by b4b4r07** [comment]
@dtan4 

Sorry! Could you fix the `./misc/scripts/install-devel-deps.sh` as the following?

```diff
diff --git a/misc/scripts/install-devel-deps.sh b/misc/scripts/install-devel-deps.sh
index 74865d8..74e4ad5 100755
--- a/misc/scripts/install-devel-deps.sh
+++ b/misc/scripts/install-devel-deps.sh
@@ -6,7 +6,7 @@ go get -v -u github.com/Songmu/ghch/cmd/ghch
 go get -v -u github.com/Songmu/goxz/cmd/goxz
 go get -v -u github.com/git-chglog/git-chglog/cmd/git-chglog
 go get -v -u github.com/golang/dep/cmd/dep
-go get -v -u github.com/golang/lint/golint
+go get -v -u golang.org/x/lint/golint
 go get -v -u github.com/haya14busa/goverage
 go get -v -u github.com/haya14busa/reviewdog/cmd/reviewdog
 go get -v -u github.com/motemen/gobump/cmd/gobump
```

Import path has been changed.

https://circleci.com/gh/mercari/tfnotify/90?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dtan4** [comment]
👌 I'll create another PR to fix it.

**Comment by b4b4r07** [comment]
Thanks!

**Pull request merged**
